### ISSUE TITLE
arXiv PDF is not available

### ISSUE THREAD

**Issue by SakurajimaMaiii** [yossigandelsman/clip_prs#1]
I am very interested in this project. 
So I want to read your paper, but arxiv pdf is not avaiable.
Is free for you to check arxiv link or upload PDF ?
Thanks for your help!
![image](https://github.com/yossigandelsman/clip_prs/assets/83657651/0235b1af-907b-47fc-81cc-53fc698ffa0f)

**Comment by yossigandelsman** [comment]
Please try again at:
https://browse.arxiv.org/pdf/2310.05916.pdf

**Comment by SakurajimaMaiii** [comment]
it works now. Thank you
