### ISSUE TITLE
A question on token decomposition

### ISSUE THREAD

**Issue by X-funbean** [yossigandelsman/clip_prs#10]
Hi, Thank you for sharing such a great work!

When playing with the visulization of token decomposition in `demo.ipynb`, I find that the `class_embedding` is L2-normalized via `class_embedding = F.normalize(class_embeddings, dim=-1)`. However, it seems that the `attentions` used to compute the attention_map with `class_embedding` are not normalized:
```Python
attention_map = attentions[0, :, 1:, :].sum(axis=(0,2)) @ class_embedding.T
```
So why not normalize the the `attentions` term when calculating the attention_map as CLIP normally does? Wouldn't it be more meaningful?

**Comment by yossigandelsman** [comment]
The normalization process is done in the `finalize` function already. So there is no need for additional normalization.
