### ISSUE TITLE
Queries on MultiheadAttention implementation

### ISSUE THREAD

**Issue by thapaliya19** [yossigandelsman/clip_prs#2]
In the `utils/transformer.py` file, a custom `MultiheadAttention` layer is implemented, while in other works like `clip` and `open_clip`, they use the pytorch's implementation of `MultiheadAttention`. Is there any specific reason for doing so? Also, any details on the different "attention methods" in the `forward()` method?

**Comment by yossigandelsman** [comment]
This layer implementation is mathematically equivalent to the `clip` and `open_clip` implementations. The difference is mostly in the ability to split the output into individual contributions of single heads and single tokens. The different versions allow me to save different intermediate parts of the computation via the `hook`.
