### ISSUE TITLE
Queries on Equation 5 and 6 Notations

### ISSUE THREAD

**Issue by chu7zpah** [yossigandelsman/clip_prs#3]
Hi, Thank you for sharing such a great work!

While reading, I have two questions regarding Eqs. 5 and 6:
1. In Eq. 5, what do the transition matrices $W_{VO}^{l, h}$ represent? I understand that Eq. 5 is the formal definition of the CLS token for layer $l$ following [Elhage et al.](https://transformer-circuits.pub/2021/framework/index.html), but I'm a bit confused about the role of $W_{VO}^{l, h}$. Could you please provide more details about what "transition" refers to?
2. In Eq. 6, does $T^{l-1}$ refer to $Z^{l-1}$? (I guess it's a typo)

Thanks in advance!

**Comment by yossigandelsman** [comment]
Hi, thank you for your interest in the paper!

1. The $W_{VO}^{l,h}$ presents the OV circuit, discussed in [Elhage et al.](https://transformer-circuits.pub/2021/framework/index.html). This is the multiplication of the Values matrix by the Output matrix of self-attention layer, and it is split into different heads (because it is linear). 

2. Yes, you are correct. We fixed it in the [openreview version](https://openreview.net/forum?id=5Ca9sSzuDp)

**Comment by chu7zpah** [comment]
Thank you for your quick reply!

Now I understand more about Eq. 5, and I have more questions about it:

1. I thought that the dimension of $z_i^{l-1}$ and $W_{VO}^{l, h}$ should be represented by $d$ (as it is an internal logic of the ViT), but the dimension is described as $d'$ (in the sentence right after Eq. 5), which is the dimension of the joint vision-and-language space after the projection matrix $P$ (Eq. 2). Did I miss something by any chance?

2. Is there a reason for using the term $W_{VO}^{l, h}$ instead of $W_{OV}^{l, h}$? I believe the relevant part of the reference article (OV circuit) is [this section](https://transformer-circuits.pub/2021/framework/index.html#summarizing-ovqk-matrices:~:text=as%20independently%20additive.-,Attention%20Heads%20as%20Information%20Movement,-But%20if%20attention), where they define $W_{OV}=W_{O}W_{V}$ (since $W_{O}W_{V}$ always works together). I'm unclear whether $W_{OV}$ and $W_{VO}$ are equivalent, but as of now, $W_{OV}$ seems more reasonable to me because $W_{O}W_{V}z_{i}^{l-1}$ can be decomposed as: (1) calculation of the value vector ($v_{i} = W_{V}z_{i}^{l-1}$), (2) compute the result vector ($r_{i} = \alpha_{i}^{l, h}v_{i}$), and (3) compute the output vector of the head ($h_{i} = W_{O}r_{i}$).

Thanks again!

**Comment by yossigandelsman** [comment]
1. Yes, you are correct again. You did not miss anything, and it is a typo and it should be $d \times d$. We will fix it. Thank you!
2. This is indeed the OV circuit, and it is probably not the best naming from our side. Please treat it as $VO$ instead of $OV$.

**Comment by chu7zpah** [comment]
Sounds good! I will close the issue. Thanks again for the interesting work!
