### ISSUE TITLE
Whether you evaluate the direct effect of different layers on zero-shot classification accuracy on the test set or on the same validation set used to calculate the mean

### ISSUE THREAD

**Issue by Yang-bug-star** [yossigandelsman/clip_prs#4]
I would like to ask you whether you evaluate the direct effect of different layers on zero-shot classification accuracy on the test set of ImageNet or on the same validation set used to calculate the mean

**Comment by yossigandelsman** [comment]
In the code, it is on the same validation set (as we don't really care about the classification, and mostly want to see what are the changes when ablating ). For a real evaluation, like the waterbirds, we use a different set from the test set (specifically - imagenet validation set).

**Comment by Yang-bug-star** [comment]
thank you for your reply.  And I would also like to ask whether you replace MLP with mean when you conduct mean-ablating experiment for MSA

**Comment by Yang-bug-star** [comment]
> In the code, it is on the same validation set (as we don't really care about the classification, and mostly want to see what are the changes when ablating ). For a real evaluation, like the waterbirds, we use a different set from the test set (specifically - imagenet validation set).

Have you done a separate experiment to keep other modules from mean-ablating and only perform mean-ablating for the last 4 MSA layers to verify its importance? 
I think the verification experiment mentioned above is important since your observation that the performance starts to decrease significantly when the ablation begins at the last 4 layers may be attributed to too much absence of the previous layers

**Comment by yossigandelsman** [comment]
You can run it by simply modifying our code. I don't recall doing it, but my intuition is that the change will not be too big.
