### ISSUE TITLE
Here, 'base' refers to randomly ablating 10 heads, or does it refer to the original OpenCLIP? 

### ISSUE THREAD

**Issue by Yang-bug-star** [yossigandelsman/clip_prs#5]
![image](https://github.com/yossigandelsman/clip_text_span/assets/68415992/f53990c8-95ff-4e85-bdcf-b7ecf50c203c)
What is the "base" here ？ Here, 'base' refers to randomly ablating 10 heads, or does it refer to the original OpenCLIP? In the original paper, it is said to take randomly ablating 10 heads as the baseline.

**Comment by yossigandelsman** [comment]
base is the original model performance, top-random is randomly ablating the same number of head as "ours", repeating this experiment few times, and take the maximum accuracy.
