### ISSUE TITLE
Did you compare the zero-shot segmentation performance between initial clip and your proposed image tokens decompositions ?

### ISSUE THREAD

**Issue by Yang-bug-star** [yossigandelsman/clip_prs#6]

**Comment by yossigandelsman** [comment]
You can see the results here:
https://openreview.net/forum?id=5Ca9sSzuDp&referrer=%5BAuthor%20Console%5D(%2Fgroup%3Fid%3DICLR.cc%2F2024%2FConference%2FAuthors%23your-submissions)
