### ISSUE TITLE
How to unroll the direct effect to find a second-order effect and how to remove such second-order effect? Could you explain more on detail.

### ISSUE THREAD

**Issue by Yang-bug-star** [yossigandelsman/clip_prs#7]
You did a preliminary example by unrolling the direct effect of a “counting head”, but I'm not very clear about the concrete details especially on how to discove second-order effect and how to remove it

**Comment by yossigandelsman** [comment]
We had some preliminary results, but they are out-of-scope for this code-base. 
We plan to share our findings in the future.
