### ISSUE TITLE
TEXTSPAN Algorithm

### ISSUE THREAD

**Issue by toffeecat** [yossigandelsman/clip_prs#9]
Hi, author. I've been studying your work, particularly Algorithm 1. However, I wonder if it's possible for two heads in different layers to receive the same text descriptions, given that we use the full text set {ti} (i=1..M) for TEXTSPAN in all applied layers.
![image](https://github.com/yossigandelsman/clip_text_span/assets/94946328/cffa734f-7e99-4e25-a434-96950fe21976)

**Comment by yossigandelsman** [comment]
Yes. Each head can be spanned by the same texts. Empirically, it happens sometime.
